### PR TITLE
[Issue #751] fix scaling bugs and upgrade basic policy

### LINKED ISSUE #751: [pixels-scaling] fix some scaling bugs and upgrade basic policy
1. fix error path: move file `io.pixelsdb.pixels.common.turbo.MetricsCollectorProvider` from `META-INF` to `META-INF/services` 
2. fix pom.xml:  add pixels-scaling-general module to pixels root pom
3. add policy helper: add FixSized queue
4. implement basic policy according to pixels-turbo paper

### PR DESCRIPTION
**Pull request by kkzzjx**
Resolves #751

### CODE REVIEW

File: pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/scaling/policy/BasicPolicy.java [hunk 1]
```diff
@@ -19,29 +19,50 @@
...
 
 public class BasicPolicy extends Policy
 {
     private static final Logger log = LogManager.getLogger(BasicPolicy.class);
-    private static final int UPPER_BOUND = 3;
-    private static final int LOWER_BOUND = 2;
+    Integer reportPeriod = Integer.parseInt(ConfigFactory.Instance().getProperty("query.concurrency.report.period.sec"));
+    private double lastAverage = 0;
+    private int count = 0;
+    private final int scalingInQueueSize = 5 * 60 / reportPeriod;
```
Comment (bianhq) [inline pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/scaling/policy/BasicPolicy.java:33]: Is it fine to hardcode 5*60?

File: pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/scaling/policy/BasicPolicy.java [hunk 2]
```diff
@@ -19,29 +19,50 @@
...
+                count = 0;
+                lastAverage = scalingOutQueue.getAverage();
+                scalingOutQueue.clear();
+            }
+
+            if (scalingOutQueue.getAverage() > 2 && lastAverage > 2)
+            {
+                log.info("Debug: expand 100% vm");
+                scalingManager.multiplyInstance(2.0f);
+            } else if (scalingInQueue.getAverage() >= 0.25 && scalingInQueue.getAverage() < 0.5)
```
Comment (bianhq) [inline pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/scaling/policy/BasicPolicy.java:58]: Is this the basic scaling policy in the pixels-turbo paper?

File: pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/scaling/policy/helper/FixedSizeQueue.java [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+ * You should have received a copy of the Affero GNU General Public
+ * License along with Pixels.  If not, see
+ * <https://www.gnu.org/licenses/>.
+ */
+package io.pixelsdb.pixels.daemon.scaling.policy.helper;
+
+import java.util.LinkedList;
+import java.util.Queue;
+
+public class FixedSizeQueue
```
Comment (bianhq) [inline pixels-daemon/src/main/java/io/pixelsdb/pixels/daemon/scaling/policy/helper/FixedSizeQueue.java:25]: Add a javadoc to each new class, explain the usage of the class (e.g., whether this is threadsafe, what should be taken care of...), and add the `@author` and `@create yyy-mm-dd`.

**Review by bianhq — CHANGES_REQUESTED** [review]

**Review by bianhq — APPROVED** [review]
LGTM.
